### ISSUE TITLE
Plugin fails to start: URI is not absolute

### ISSUE THREAD

**Issue by Ch00k** [GoogleCloudPlatform/weasis-chcapi-extension#36]
I am running Weasis 3.6.0. I did what is says in the "Installing plugin" readme section, but the plugin fails to initialize, throwing the following exception:

```
19.05.2020 07:43:52.437 *SEVERE* [main] org.weasis.launcher.FileUtil: Cannot install bundle weasis-chcapi-extension-3.0.7
java.lang.IllegalArgumentException: URI is not absolute
	at java.base/java.net.URL.fromURI(URL.java:719)
	at java.base/java.net.URI.toURL(URI.java:1139)
	at org.weasis.launcher.AutoProcessor.installBundle(AutoProcessor.java:530)
	at org.weasis.launcher.AutoProcessor.processAutoProperties(AutoProcessor.java:351)
	at org.weasis.launcher.AutoProcessor.process(AutoProcessor.java:106)
	at org.weasis.launcher.WeasisLoader.setFelix(WeasisLoader.java:248)
	at org.weasis.launcher.WeasisLauncher.launch(WeasisLauncher.java:247)
	at org.weasis.launcher.AppLauncher.main(AppLauncher.java:27)
19.05.2020 07:43:52.450 *SEVERE* [main] org.weasis.launcher.FileUtil: Cannot start bundle weasis-chcapi-extension-3.0.7
java.lang.IllegalArgumentException: URI is not absolute
	at java.base/java.net.URL.fromURI(URL.java:719)
	at java.base/java.net.URI.toURL(URI.java:1139)
	at org.weasis.launcher.AutoProcessor.installBundle(AutoProcessor.java:530)
	at org.weasis.launcher.AutoProcessor.processAutoProperties(AutoProcessor.java:389)
	at org.weasis.launcher.AutoProcessor.process(AutoProcessor.java:106)
	at org.weasis.launcher.WeasisLoader.setFelix(WeasisLoader.java:248)
	at org.weasis.launcher.WeasisLauncher.launch(WeasisLauncher.java:247)
	at org.weasis.launcher.AppLauncher.main(AppLauncher.java:27)
```

**Comment by Ch00k** [comment]
Ok, this is weird, but I can't reproduce it anymore. Now the plugin is not even tried to be loaded it looks like. The only line I have in `/Applications/Weasis.app/Contents/app/conf/ext-config.properties` is this:

```
felix.auto.start.85=${weasis.codebase.url}/plugins/weasis-chcapi-extension-3.0.7.jar
```

I also have the secrets file at `/Users/ay/.weasis/client_secrets.json`. Weasis starts up, but I don't see the Google Healthcare Explorer tab, nor am I being asked to login anywhere.

**Comment by dzelemba** [comment]
Hi Andrii,

The latest supported Weasis release for this plugin is Weasis 3.0.4 (https://github.com/nroduit/Weasis/releases/tag/3.0.4). Does that release work for you?

Thanks,
Dusan

**Comment by Ch00k** [comment]
I did not pay enough attention to the readme, sorry for that.
Are there any plans to make the plugin compatible with the latest Weasis?

**Comment by dzelemba** [comment]
Not at the moment, but I did file a FR: https://github.com/GoogleCloudPlatform/weasis-chcapi-extension/issues/37 that you can follow.

I also filled a FR (https://github.com/nroduit/Weasis/issues/125) in the Weasis repo to enhance their native integration functionality.

You could also check out OHIF as an alternative OSS viewer integrated with the Healthcare API: https://docs.ohif.org/connecting-to-image-archives/google-cloud-healthcare.html.

**Comment by Ch00k** [comment]
Thanks! I'll follow those 2 issues.
OHIF is awesome, and actually fits best for the scenarios I want to use a DICOM viewer in (in terms of deployment anyway), but unfortunately it does not support GSPS.
