### ISSUE TITLE
Support Weasis v3.6 on MacOS

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/weasis-chcapi-extension#37]

**Comment by arvgord** [comment]
I tested the current version of extension with Weasis v3.6 and found that the current version of the extension supports Weasis v3.6.

**Comment by dzelemba** [comment]
What OS did you try it on? I've tried using the native installer for MacOS and was able to reproduce the issue mentioned in https://github.com/GoogleCloudPlatform/weasis-chcapi-extension/issues/36#issuecomment-630610228.

**Comment by dzelemba** [comment]
The portable version doesn't seem to work on MacOS anymore (the viewer-mac file is broken).

**Comment by arvgord** [comment]
I tested on Ubuntu 20.04. New update works for installed Weasis. I think that new update should work for macOS. But I'll test new update for macOS.

**Comment by poojavenkatram** [comment]
I am able to run install the plugin on Mac but seeing an error after Google Sign In and clicking the down arrow. I have more details in the attached screenshot.
![image](https://user-images.githubusercontent.com/6560374/82924203-021be400-9f4a-11ea-8127-46cf8d34db31.png)

**Comment by dzelemba** [comment]
I hit the same error mentioned above. This was after clearing local cached files in ~/.weasis as well.

**Comment by dzelemba** [comment]
Also the [install instructions](https://github.com/GoogleCloudPlatform/weasis-chcapi-extension#installing-plugin) seem to be out of date... you don't need to copy client secrets anymore, right?

**Comment by arvgord** [comment]
I can reproduce `java.lang.IllegalArgumentException: URI is not absolute`.
To avoid that issue you should use URI path on macOS: **felix.auto.start.85=file:///Users/Username/path/to/weasis-chcapi-extension-3.0.8.jar** 
I created PR with explanation.
I tested the plugin with last updates on all platforms. It works without any issue.
![macOS](https://user-images.githubusercontent.com/39695947/83028734-059f9000-a05c-11ea-8b7b-0fbd5b2a3ef5.png)
> Also the install instructions seem to be out of date... you don't need to copy client secrets anymore, right?  

Administrator or user can manage access using another client_secret.json

**Comment by dzelemba** [comment]
Hmm did you use the native installer for MacOS? I'm still getting the "unexpected error on fetching google api: null" error even if I use an absolute path.

>Administrator or user can manage access using another client_secret.json

Yes but this isn't required, right? The instructions make it sound like everyone has to do this.

**Comment by arvgord** [comment]
> Hmm did you use the native installer for MacOS?

Yes, I used native installer. Could you delete .Weasis folder and start Weasis again?
> Yes but this isn't required, right? The instructions make it sound like everyone has to do this.

I agree with you. Should I remove these instructions from README.md or rewrite for better understanding?

**Comment by dzelemba** [comment]
Tried deleting ~/.weasis and it successfully forced reload of plugins and made me re-sign in, but same error. Is there any error log I could share?

And I think we can just remove that part of the instructions.

**Comment by arvgord** [comment]
> Is there any error log I could share?

Could you start Weasis using console?

> And I think we can just remove that part of the instructions.

Ok.

**Comment by dzelemba** [comment]
I tried `open /Applications/weasis.app` but no console logs were printed. Should I invoke the JAR directly somehow?

**Comment by arvgord** [comment]
> I tried open /Applications/weasis.app but no console logs were printed. Should I invoke the JAR directly somehow?

Open console:
```
cd /Applications/Weasis.app/Contents/MacOS
./Weasis
```

**Comment by dzelemba** [comment]
```
27.05.2020 14:05:15.302 *ERROR* [AWT-EventQueue-0] org.weasis.dicom.google.api.ui.dicomstore.AbstractDicomSelectorTask: Error on dicom task java.lang.NullPointerException
	at java.base/java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:469)
	at java.base/java.util.TimSort.binarySort(TimSort.java:296)
	at java.base/java.util.TimSort.sort(TimSort.java:239)
```

This bug is familiar I feel like we fixed it in some other repo as well. I think it's because not all GCP projects returned will have a createTime for some reason.

**Comment by Ch00k** [comment]
I could make the extension initialize, and I do have its controls on Weasis UI, so thanks a lot for making it work!
When I try to login with my Google account though, I get this error
<img width="457" alt="Screenshot 2020-06-01 at 11 03 57" src="https://user-images.githubusercontent.com/230214/83399072-dc3a8780-a400-11ea-861a-a3acfb131c37.png">
Is it some kind of an organization policy that denies OAuth2 logins, or am I missing something else?

**Comment by dzelemba** [comment]
This is due to your organization's policy restricting which apps can access your Google Cloud data. You can either reach out to your org to get this app whitelisted or just create your own client ID and use that (https://github.com/GoogleCloudPlatform/weasis-chcapi-extension/blob/master/README.md#using-your-own-oauth-client). I'm having some issues getting this to work at the moment though: https://github.com/GoogleCloudPlatform/weasis-chcapi-extension/issues/42.

**Comment by arvgord** [comment]
@dzelemba 
Nicolas successfully added my [changes](https://github.com/nroduit/nroduit.github.io/pull/1) to [weasis](https://nroduit.github.io/en/basics/customize/build-plugins/) site.
I can reproduce the ERROR mentioned above.
I found than some of your projects may have a null name or id, so that I created [PR](https://github.com/GoogleCloudPlatform/weasis-chcapi-extension/pull/43) that should fix this.

**Comment by poojavenkatram** [comment]
With that NPE fix, the app is not even loading anymore(if I try again it loads without the plugin). When I run on terminal I see the below error: 
02.06.2020 11:19:37.580 *SEVERE* [main] org.weasis.launcher.FileUtil: Cannot install bundle weasis-chcapi-extension-3.0.9
java.net.UnknownHostException: Applications
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:961)
	at java.base/sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:923)
	at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1018)
	at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1004)
	at java.base/sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:319)
	at java.base/sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:425)
	at org.weasis.launcher.AutoProcessor.installBundle(AutoProcessor.java:530)
	at org.weasis.launcher.AutoProcessor.processAutoProperties(AutoProcessor.java:351)
	at org.weasis.launcher.AutoProcessor.process(AutoProcessor.java:106)
	at org.weasis.launcher.WeasisLoader.setFelix(WeasisLoader.java:248)
	at org.weasis.launcher.WeasisLauncher.launch(WeasisLauncher.java:247)
	at org.weasis.launcher.AppLauncher.main(AppLauncher.java:27)
02.06.2020 11:19:37.594 *SEVERE* [main] org.weasis.launcher.FileUtil: Cannot start bundle weasis-chcapi-extension-3.0.9
java.net.UnknownHostException: Applications
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:961)
	at java.base/sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:923)
	at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1018)
	at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1004)
	at java.base/sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:319)
	at java.base/sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:425)
	at org.weasis.launcher.AutoProcessor.installBundle(AutoProcessor.java:530)
	at org.weasis.launcher.AutoProcessor.processAutoProperties(AutoProcessor.java:389)
	at org.weasis.launcher.AutoProcessor.process(AutoProcessor.java:106)
	at org.weasis.launcher.WeasisLoader.setFelix(WeasisLoader.java:248)
	at org.weasis.launcher.WeasisLauncher.launch(WeasisLauncher.java:247)
	at org.weasis.launcher.AppLauncher.main(AppLauncher.java:27)

**Comment by poojavenkatram** [comment]
I removed client_secrets.json because it is not necessary..

**Comment by arvgord** [comment]
@poojavenkatram  Please check your path to the extension.
Example path:
**felix.auto.start.85=file:///Users/Username/path/to/weasis-chcapi-extension-3.0.9**

**Comment by poojavenkatram** [comment]
This is the path I have:
felix.auto.start.85=file://Applications/Weasis.app/Contents/app/plugins/weasis-chcapi-extension-3.0.9.jar

I used the same path for 3.0.8.jar and it worked then just changed the 3.0.8 to 3.0.9 this time..

**Comment by arvgord** [comment]
I see you missed one slash in path.

**Comment by poojavenkatram** [comment]
Actually it was my bad..had only 2//

**Comment by poojavenkatram** [comment]
hehe yeah just realized

**Comment by poojavenkatram** [comment]
Thanks a lot checking..

**Comment by poojavenkatram** [comment]
Now the projects are loading but getting a NPE when loading DICOM Stores: 02.06.2020 12:06:26.464 *ERROR* [AWT-EventQueue-0] org.weasis.dicom.google.api.ui.dicomstore.AbstractDicomSelectorTask: Error on dicom task java.lang.NullPointerException
	at org.weasis.dicom.google.api.GoogleAPIClient.fetchDicomstores(GoogleAPIClient.java:365)
	at org.weasis.dicom.google.api.ui.dicomstore.LoadDicomStoresTask.doInBackground(LoadDicomStoresTask.java:37)
	at org.weasis.dicom.google.api.ui.dicomstore.LoadDicomStoresTask.doInBackground(LoadDicomStoresTask.java:24)

**Comment by poojavenkatram** [comment]
Actually think we are not handling the case for a Dataset with no DICOM Stores...

**Comment by poojavenkatram** [comment]
Will file a different issue for that. I am able to view the image with the latest version. @arvgord thanks so much for fixing this :)
