### ISSUE TITLE
Have a nice message when a Dataset does not have any DICOM Stores

### ISSUE THREAD

**Issue by poojavenkatram** [GoogleCloudPlatform/weasis-chcapi-extension#44]
Right now a pop-up comes up with "unexpected error when fetching google api: null" 
Instead, it would be nicer to handle this and pop up: "No DICOM Stores in Dataset"
12:06:26.464 ERROR [AWT-EventQueue-0] org.weasis.dicom.google.api.ui.dicomstore.AbstractDicomSelectorTask: Error on dicom task java.lang.NullPointerException
at org.weasis.dicom.google.api.GoogleAPIClient.fetchDicomstores(GoogleAPIClient.java:365)
at org.weasis.dicom.google.api.ui.dicomstore.LoadDicomStoresTask.doInBackground(LoadDicomStoresTask.java:37)
at org.weasis.dicom.google.api.ui.dicomstore.LoadDicomStoresTask.doInBackground(LoadDicomStoresTask.java:24)

**Comment by poojavenkatram** [comment]
Works nicely thanks :)
